import {useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {DateTime} from 'luxon';
import {api,useApi,refreshData} from './api';
import {PageTitle,Load,Field,money,dateTime,useAction,Badge} from './ui';
import type {Items,Salon,Catalog} from './types';

type Promotion={id:string;providerTenantId:string;proposerTenantId:string;status:string;version:number;activeVersionId:string|null;pendingVersionId:string|null;acceptedByMe:boolean;title:string;termsText:string;serviceIds:string[];discountType:'fixed'|'percent';fixedDiscountMinor:number|null;discountPercent:number|null;startsAt:string;endsAt:string;useLimit:number|null;usedTotal:number;reservedTotal:number};
type PublicPromotion={id:string;providerTenantId:string;publicCode:string;providerName:string;title:string;termsText:string;serviceIds:string[];discountType:'fixed'|'percent';fixedDiscountMinor:number|null;discountPercent:number|null;startsAt:string;endsAt:string;useLimit:number|null;usedTotal:number};
const discount=(p:{discountType:string;fixedDiscountMinor:number|null;discountPercent:number|null})=>p.discountType==='fixed'?money(p.fixedDiscountMinor):`${p.discountPercent}%`;
export function PromotionCards(){const data=useApi<Items<PublicPromotion>>('/me/promotions',true);return <><h2>Временные акции</h2><Load {...data}>{data.data?.items.length?<div className="two-columns">{data.data.items.map(p=><section className="panel" key={p.id}><span className="eyebrow">{p.providerName}</span><h3>{p.title}</h3><p>{p.termsText}</p><p><strong>−{discount(p)}</strong> · до {dateTime(p.endsAt)}</p><Link className="button primary" to={`/s/${p.publicCode}/book?promotion=${p.id}&service=${p.serviceIds[0]}`}>Выбрать время</Link></section>)}</div>:<p className="muted">Сейчас нет доступных акций.</p>}</Load></>;}
export function PromotionsWorkPage(){
  const {t}=useParams();const data=useApi<Items<Promotion>>(`/work/${t}/promotions`,true);
  const salon=useApi<Salon>(`/work/${t}/profile`);const salons=useApi<Items<Salon>>('/public/salons');
  const [provider,setProvider]=useState(t??'');const providerCode=salons.data?.items.find(s=>s.id===provider)?.publicCode;const catalog=useApi<Catalog>(providerCode?`/public/salons/${providerCode}/catalog`:null);
  const [selected,setSelected]=useState<string[]>([]);const [title,setTitle]=useState('');const [conditions,setConditions]=useState('');const [type,setType]=useState<'fixed'|'percent'>('percent');const [amount,setAmount]=useState(10);const [start,setStart]=useState('');const [end,setEnd]=useState('');const [limit,setLimit]=useState('');const [editing,setEditing]=useState<Promotion|null>(null);
  const action=useAction();const zone=provider===t?salon.data?.timezone??'Europe/Moscow':salons.data?.items.find(s=>s.id===provider)?.timezone??'Europe/Moscow';
  const toInstant=(value:string)=>DateTime.fromISO(value,{zone}).toUTC().toISO();
  const startVersion=(p:Promotion)=>{
    const targetZone=p.providerTenantId===t?salon.data?.timezone??'Europe/Moscow':salons.data?.items.find(s=>s.id===p.providerTenantId)?.timezone??'Europe/Moscow';
    setEditing(p);setProvider(p.providerTenantId);setTitle(p.title);setConditions(p.termsText);setSelected(p.serviceIds);setType(p.discountType);
    setAmount(p.discountType==='fixed'?(p.fixedDiscountMinor??0)/100:p.discountPercent??0);
    setStart(DateTime.fromISO(p.startsAt).setZone(targetZone).toFormat("yyyy-MM-dd'T'HH:mm"));
    setEnd(DateTime.fromISO(p.endsAt).setZone(targetZone).toFormat("yyyy-MM-dd'T'HH:mm"));setLimit(p.useLimit?.toString()??'');
  };
  return <><PageTitle title="Временные акции" description="Свои акции публикуются сразу. Акция на услуги партнёра действует после его подтверждения."/>
    <section className="panel"><h2>{editing?'Новая версия акции':'Создать акцию'}</h2><div className="two-columns"><Field label="Салон-исполнитель"><select value={provider} disabled={!!editing} onChange={e=>{setProvider(e.target.value);setSelected([]);}}><option value={t}>Наш салон</option>{salons.data?.items.filter(s=>s.id!==t).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="Заголовок"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Условия"><textarea value={conditions} onChange={e=>setConditions(e.target.value)}/></Field><Field label="Услуги"><div>{catalog.data?.services.filter(s=>s.active).map(s=><label className="check" key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{s.name}</label>)}</div></Field><Field label="Тип скидки"><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="percent">Процент</option><option value="fixed">Рубли</option></select></Field><Field label={type==='percent'?'Размер, %':'Размер, ₽'}><input type="number" min={1} max={type==='percent'?100:undefined} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field><Field label={`Начало (${zone})`}><input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label={`Окончание (${zone})`}><input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="Лимит применений (пусто — без лимита)"><input type="number" min={1} value={limit} onChange={e=>setLimit(e.target.value)}/></Field></div><button className="button primary" disabled={action.busy||!title||!conditions||!selected.length||!start||!end} onClick={()=>void action.run(async()=>{const body={providerTenantId:provider,title,termsText:conditions,serviceIds:selected,discountType:type,fixedDiscountMinor:type==='fixed'?Math.round(amount*100):null,discountPercent:type==='percent'?amount:null,startsAt:toInstant(start),endsAt:toInstant(end),useLimit:limit?Number(limit):null,...(editing?{expectedVersion:editing.version}:{})};await api(`/work/${t}/promotions${editing?`/${editing.id}/versions`:''}`,'POST',body);setEditing(null);refreshData();},'Акция сохранена')}>{editing?'Предложить новую версию':provider===t?'Опубликовать':'Отправить на согласование'}</button>{action.feedback}</section>
    <h2>Акции салона</h2><Load {...data}>{data.data?.items.map(p=><section className="panel" key={p.id}><div className="section-head"><h3>{p.title??'Предложение'}</h3><Badge status={p.status}/></div><p>{p.termsText}</p><p>−{discount(p)} · {p.endsAt?dateTime(p.endsAt):'ожидает согласования'} · использовано {p.usedTotal??0}{p.useLimit?` из ${p.useLimit}`:''} · в резерве {p.reservedTotal??0}</p>{p.pendingVersionId&&<p className="notice">Новая версия ожидает согласования. До подтверждения действуют прежние условия.</p>}<div className="inline-actions">{p.pendingVersionId&&!p.acceptedByMe&&<><button className="button primary" disabled={action.busy} onClick={()=>void action.run(async()=>{await api(`/work/${t}/promotions/${p.id}/accept`,'POST',{expectedVersion:p.version});refreshData();},'Акция подтверждена')}>Подтвердить</button><button className="button secondary" disabled={action.busy} onClick={()=>void action.run(async()=>{await api(`/work/${t}/promotions/${p.id}/reject`,'POST',{expectedVersion:p.version});refreshData();},'Предложение отклонено')}>Отклонить</button></>}{p.activeVersionId&&<><button className="button secondary" onClick={()=>startVersion(p)}>Новая версия</button>{['pause','resume','end'].map(kind=><button key={kind} className="button secondary" disabled={action.busy} onClick={()=>void action.run(async()=>{await api(`/work/${t}/promotions/${p.id}/${kind}`,'POST',{expectedVersion:p.version});refreshData();},'Статус обновлён')}>{kind==='pause'?'Пауза':kind==='resume'?'Продолжить':'Завершить'}</button>)}</>}</div></section>)}</Load></>;
}
