function desktopLinks(){
  if(state.role==='master')return [['masterDay','Мои записи'],['masterVisit','Визит'],['role','Сменить кабинет']];
  if(state.role!=='client')return [['workHome','Сегодня'],['calendar','Календарь'],['customers','Клиенты'],['programs','Лояльность'],['catalog','Услуги'],['schedule','График'],['analytics','Статистика'],['workPromos','Акции'],['access','Команда']];
  if(state.concept==='b')return [['home','Поиск времени'],['discover','Результаты'],['bookings','Мои визиты'],['waitlist','Живое окно'],['offers','Предложения'],['profile','Профиль']];
  if(state.concept==='c')return [['home','Мои места'],['salon','Салон'],['bookings','Мои визиты'],['loyalty','Мои бонусы'],['events','События'],['profile','Профиль']];
  if(state.concept==='bc')return [['home','Поиск и места'],['discover','Карточки салонов'],['salon','Мой салон'],['bookings','Мои визиты'],['waitlist','Живое окно'],['loyalty','Награды'],['profile','Профиль']];
  return [['home','Главная'],['discover','Найти салон'],['bookings','Мои записи'],['waitlist','Живое окно'],['loyalty','Награды'],['events','События'],['profile','Профиль']];
}
function desktopContext(){
  if(state.role==='master'){const date=new Date(state.masterYear,state.masterMonth,state.masterDate).toLocaleDateString('ru-RU',{day:'numeric',month:'long'}),count=masterAppointments(state.masterDate).length;return `<span class="kicker">МОИ НАЗНАЧЕНИЯ</span><h3>${date}</h3><div class="context-stat"><b>${count}</b><span>${count===1?'запись':count>1&&count<5?'записи':'записей'} в выбранный день</span></div><hr class="divider">${card('Мой календарь','Выбрать другой день','masterDay')}<p class="mini">В кабинете мастера видны только свои записи.</p>`}
  if(state.role!=='client'){const count=ownerVisibleAppointments(state.ownerDate).filter(x=>!x.live).length;return `<span class="kicker">РАБОЧИЙ КОНТЕКСТ</span><h3>«Линия»</h3><div class="context-stat"><b>${count}</b><span>${recordWord(count)} в выбранный день</span></div><hr class="divider">${card('Календарь салона','Все мастера и записи','calendar')}${card('Лояльность','Программы и партнёры','programs')}`}
  if(state.concept==='a')return `<span class="kicker">ВАШ ПУТЬ</span><h3>Спокойно, шаг за шагом</h3><ol class="desktop-steps"><li><b>Выберите место</b><span>Знакомый салон или новый</span></li><li><b>Найдите время</b><span>Один выбор за раз</span></li><li><b>Проверьте итог</b><span>Цена и условия до записи</span></li></ol>${card('Ближайший визит',`${h(state.booking.date)} · ${h(state.booking.time)}`,'booking')}${card('Нужна помощь с временем?','Оставить пожелания','waitForm')}`;
  if(state.concept==='b')return `<span class="kicker">ПОИСК ВРЕМЕНИ</span><h3>Быстрый выбор</h3><p class="mini">Начните с подходящего момента, затем сравните салон, мастера и цену.</p>${chips([['Сегодня','Сегодня'],['Завтра','Завтра'],['29 сен','29 сентября']],state.date,'date')}<div class="context-stat"><b>3</b><span>варианта после 12:00</span></div>${card('Сравнить варианты','Конкретное время и цена','discover')}${card('Нет нужного времени','Получить предложение','waitForm')}`;
  if(state.concept==='bc')return `<span class="kicker">ВАШ ПОИСК</span><h3>Время и знакомые места</h3><p class="mini">Параметры выбора — сверху. В карточках салонов видны ближайшее окно, цена и ваш контекст.</p><div class="context-stat"><b>${state.searchService==='Любая'?'3':'1'}</b><span>подходящих места</span></div>${card('Ваш следующий визит',`${h(state.booking.date)} · ${h(state.booking.time)}`,'booking')}${card('Доступная награда','В «Линии»','loyalty')}${card('Изменить параметры','Услуга, день и время','home')}`;
  let current=state.screen==='home'?'Линия':state.salon;return `<span class="kicker">МОЁ МЕСТО</span><h3>«${h(current)}»</h3><p class="mini">Ваши люди, визиты и награды остаются рядом с выбранным салоном.</p>${card('Следующий визит',`${h(state.booking.date)} · ${h(state.booking.time)}`,'booking')}${current==='Линия'?card('Доступная награда','Бесплатное посещение','loyalty'):''}${card('Услуги салона','Выбрать новый визит','salon')}`;
}
function desktopPreview(){
  if(state.role!=='client'&&(['customers','workHome'].includes(state.screen)||state.concept!=='c'&&['calendar','live'].includes(state.screen)))return `<div class="desktop-preview"><p class="device-label">РАБОЧИЙ КАБИНЕТ · ШИРОКИЙ ЭКРАН</p>${wide()}</div>`;
  const role=state.role==='client'?'Личный кабинет':state.role==='master'?'Кабинет мастера':state.role==='admin'?'Кабинет администратора':'Кабинет владельца';
  return `<div class="desktop-preview"><p class="device-label">ВЕБ-ПРИЛОЖЕНИЕ · ШИРОКИЙ ЭКРАН</p><div class="app-screen ${state.concept} desktop-product"><aside class="desktop-rail"><div class="desktop-logo">ря<span>дом</span></div><div class="desktop-rail-caption">${h(role)}</div><nav aria-label="Навигация веб-приложения">${desktopLinks().map(([id,label])=>`<button data-go="${id}" class="${state.screen===id?'active':''}">${label}</button>`).join('')}</nav><button class="desktop-switch" data-go="role">Сменить кабинет ↗</button></aside><div class="desktop-workspace"><header class="desktop-bar"><span>${state.role==='client'?'Для вас':`Линия / ${h(role)}`}</span><span>Москва · 29 сентября 2026</span></header><div class="desktop-columns"><main class="desktop-content">${contents()}</main><aside class="desktop-context">${desktopContext()}</aside></div></div></div></div>`;
}
