import type { FastifyInstance } from 'fastify';
import { DateTime } from 'luxon';
import { route,list,page } from './http.js';
import { one,rows } from '../db/db.js';
import { fail,required } from './errors.js';
import { tenantById } from './salons.routes.js';
export function analyticsRoutes(app:FastifyInstance){
  route(app,'GET','/api/v1/work/:t/analytics',{roles:['owner','admin'],description:'Периодные метрики, стоимость услуг и загрузка по сохранённым графикам'},async({db,member,p,q})=>{
    const tenant=await tenantById(db,p.t!);const from=DateTime.fromISO(q.from??DateTime.now().startOf('month').toISODate()!,{zone:tenant.timezone}).startOf('day'),to=DateTime.fromISO(q.to??DateTime.now().toISODate()!,{zone:tenant.timezone}).plus({days:1}).startOf('day');if(!from.isValid||!to.isValid||to<=from||to.diff(from,'days').days>366)fail(422,'VALIDATION_ERROR','Выберите период от 1 до 366 дней');
    const args=[p.t,from.toJSDate(),to.toJSDate(),q.staffId||null];
    const counts=(await one<{planned:number;completed:number;cancelled:number;no_show:number;service_value_minor:number;occupied_minutes:number}>(db,"SELECT count(*) FILTER(WHERE status='confirmed')::int planned,count(*) FILTER(WHERE status='completed')::int completed,count(*) FILTER(WHERE status='cancelled')::int cancelled,count(*) FILTER(WHERE status='no_show')::int no_show,COALESCE(sum(price_minor_snapshot-discount_minor) FILTER(WHERE status='completed'),0)::bigint service_value_minor FROM bookings WHERE tenant_id=$1 AND start_at>=$2 AND start_at<$3 AND ($4::uuid IS NULL OR staff_id=$4)",args))!;
    const created=(await one<{count:number}>(db,'SELECT count(*)::int count FROM bookings WHERE tenant_id=$1 AND created_at>=$2 AND created_at<$3 AND ($4::uuid IS NULL OR staff_id=$4)',args))!.count;
    const occupied=(await one<{minutes:number}>(db,"SELECT COALESCE(sum(extract(epoch FROM (LEAST(end_at,$3)-GREATEST(start_at,$2)))/60),0)::float8 minutes FROM bookings WHERE tenant_id=$1 AND start_at<$3 AND end_at>$2 AND status<>'cancelled' AND ($4::uuid IS NULL OR staff_id=$4)",args))!.minutes;
    const denom=(await one<{minutes:number;days:number}>(db,'SELECT COALESCE(sum(available_minutes),0)::float8 minutes,count(*)::int days FROM schedule_snapshots WHERE tenant_id=$1 AND local_date>=$2::date AND local_date<$3::date AND ($4::uuid IS NULL OR staff_id=$4)',[p.t,from.toISODate(),to.toISODate(),q.staffId||null]))!;
    const customers=(await one<{new_customers:number;returning_customers:number}>(db,"WITH firsts AS (SELECT customer_id,min(start_at) first_at FROM bookings WHERE tenant_id=$1 AND status='completed' GROUP BY customer_id), visited AS (SELECT DISTINCT customer_id FROM bookings WHERE tenant_id=$1 AND status='completed' AND start_at>=$2 AND start_at<$3 AND ($4::uuid IS NULL OR staff_id=$4)) SELECT count(*) FILTER(WHERE f.first_at>=$2)::int new_customers,count(*) FILTER(WHERE f.first_at<$2)::int returning_customers FROM visited v JOIN firsts f USING(customer_id)",args))!;
    const all=counts.planned+counts.completed+counts.cancelled+counts.no_show;
    const result:Record<string,unknown>={created,planned:counts.planned,completed:counts.completed,cancelled:counts.cancelled,noShow:counts.no_show,noShowRate:counts.completed+counts.no_show?counts.no_show/(counts.completed+counts.no_show):null,cancellationRate:all?counts.cancelled/all:null,...customers,occupiedMinutes:occupied,availableMinutes:denom.days?denom.minutes:null,utilization:denom.minutes?occupied/denom.minutes:null,calculatedAt:new Date(),timezone:tenant.timezone,from:from.toISODate(),to:to.minus({days:1}).toISODate(),snapshotDays:denom.days};
    if(member.role==='owner'){result.serviceValueMinor=Number(counts.service_value_minor);result.averageVisitMinor=counts.completed?Math.round(Number(counts.service_value_minor)/counts.completed):null;}
    result.services=await rows(db,"SELECT service_name_snapshot name,count(*)::int count FROM bookings WHERE tenant_id=$1 AND start_at>=$2 AND start_at<$3 AND status='completed' AND ($4::uuid IS NULL OR staff_id=$4) GROUP BY service_name_snapshot ORDER BY count DESC",args);return result;
  });
  route(app,'GET','/api/v1/work/:t/campaigns/:id/analytics',{roles:['owner'],description:'Конверсия когорты выданных купонов без клиентов другого салона'},async({db,p,q})=>{required(await one(db,'SELECT id FROM campaigns WHERE id=$1 AND (source_tenant_id=$2 OR target_tenant_id=$2)',[p.id,p.t]));const tenant=await tenantById(db,p.t!);const from=DateTime.fromISO(q.from??DateTime.now().startOf('month').toISODate()!,{zone:tenant.timezone}).startOf('day'),to=DateTime.fromISO(q.to??DateTime.now().toISODate()!,{zone:tenant.timezone}).plus({days:1}).startOf('day');if(!from.isValid||!to.isValid||to<=from||to.diff(from,'days').days>366)fail(422,'VALIDATION_ERROR','Некорректный период');const result=(await one<{issued:number;redeemed:number;reserved:number;expired:number;revoked:number}>(db,"SELECT count(*)::int issued,count(*) FILTER(WHERE status='redeemed')::int redeemed,count(*) FILTER(WHERE status='reserved')::int reserved,count(*) FILTER(WHERE status='expired')::int expired,count(*) FILTER(WHERE status='revoked')::int revoked FROM vouchers WHERE campaign_id=$1 AND issued_at>=$2 AND issued_at<$3",[p.id,from.toJSDate(),to.toJSDate()]))!;return {...result,conversion:result.issued?result.redeemed/result.issued:null,calculatedAt:new Date()};});
  route(app,'GET','/api/v1/work/:t/audit',{roles:['owner','admin'],description:'Журнал действий разрешённых областей'},async({db,member,p,q})=>{const {limit,offset}=page(q);const result=await rows(db,"SELECT a.id,a.action,a.object_id,a.details,a.created_at,u.display_name actor_name FROM audit_log a LEFT JOIN users u ON u.id=a.actor_id WHERE a.tenant_id=$1 AND ($2::text IS NULL OR a.action LIKE $2||'%') AND ($3 OR a.action ~ '^(booking|catalog|schedule|crm)\\.') ORDER BY a.created_at DESC,a.id LIMIT $4 OFFSET $5",[p.t,q.kind||null,member.role==='owner',limit+1,offset]);return {items:result.slice(0,limit),nextCursor:result.length>limit?String(offset+limit):null};});
  route(app,'GET','/api/v1/work/:t/delivery-failures',{roles:['owner','admin'],description:'Состояние доставки сообщений своего салона'},async({db,p,member,actor})=>{const t=await tenantById(db,p.t!);if(member.role!=='owner'&&t.operational_recipient_id!==actor.id)fail(403,'FORBIDDEN','Состояние доставки доступно назначенному получателю');return list(await rows(db,"SELECT d.id,d.state,d.category,d.last_error,d.attempts,d.created_at,n.title FROM deliveries d JOIN notifications n ON n.id=d.notification_id WHERE d.tenant_id=$1 AND d.state IN ('failed','retry_wait','suppressed') ORDER BY d.created_at DESC LIMIT 100",[p.t]));});
}
