import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { one, rows, type DB } from '../db/db.js';
import { route,audit,list } from './http.js';
import { fail,required,version } from './errors.js';
import { expected,command,campaignTerms,id,reason } from '../contracts/schemas.js';
import type { Campaign,CampaignVersion,Tenant,Voucher,Booking } from './types.js';
import { canonical,hash } from './auth.js';
import { notify,bookingEvent } from './notifications.js';
import { bookingRevision,voucherRevision } from './bookings.js';
import { tenantById } from './salons.routes.js';

type Terms=z.infer<typeof campaignTerms>;
async function campaign(db:DB,tenant:string,id:string){return required(await one<Campaign>(db,'SELECT * FROM campaigns WHERE id=$1 AND (source_tenant_id=$2 OR target_tenant_id=$2)',[id,tenant]));}
async function validateTerms(db:DB,c:Campaign,b:Terms){
  if(new Date(b.issueUntil)<=new Date(b.issueFrom))fail(422,'VALIDATION_ERROR','Конец выдачи должен быть позже начала');
  if(b.issueLimit<c.issued_total)fail(422,'VALIDATION_ERROR','Общий лимит нельзя уменьшить ниже уже выданного количества');
  for(const [tenantId,ids,target] of [[c.source_tenant_id,b.sourceServiceIds,false],[c.target_tenant_id,b.targetServiceIds,true]] as [string,string[],boolean][]) {
    const services=await rows<{id:string;price_minor:number}>(db,'SELECT id,price_minor FROM services WHERE tenant_id=$1 AND active AND id=ANY($2::uuid[])',[tenantId,ids]);
    if(services.length!==new Set(ids).size)fail(422,'VALIDATION_ERROR','Услуги должны быть активны и принадлежать соответствующему салону');
    if(target&&services.some(s=>s.price_minor<b.discountMinor))fail(422,'VALIDATION_ERROR','Скидка превышает стоимость принимающей услуги');
  }
}
async function insertVersion(db:DB,c:Campaign,b:Terms){await validateTerms(db,c,b);return one<CampaignVersion>(db,"INSERT INTO campaign_versions(campaign_id,number,source_service_ids,target_service_ids,discount_minor,issue_from,issue_until,voucher_valid_days,issue_limit,terms_text,terms_hash) SELECT $1,COALESCE(max(number),0)+1,$2,$3,$4,$5,$6,$7,$8,$9,$10 FROM campaign_versions WHERE campaign_id=$1 RETURNING *",[c.id,b.sourceServiceIds,b.targetServiceIds,b.discountMinor,b.issueFrom,b.issueUntil,b.voucherValidDays,b.issueLimit,b.termsText,hash(canonical(b))]);}
async function campaignView(db:DB,c:Campaign){return {...c,versions:await rows(db,'SELECT v.*,COALESCE((SELECT jsonb_agg(jsonb_build_object(\'tenantId\',a.tenant_id,\'acceptedAt\',a.created_at)) FROM campaign_acceptances a WHERE a.version_id=v.id),\'[]\') acceptances FROM campaign_versions v WHERE campaign_id=$1 ORDER BY number DESC',[c.id]),pauses:await rows(db,'SELECT p.*,t.name tenant_name FROM campaign_pauses p JOIN tenants t ON t.id=p.tenant_id WHERE campaign_id=$1',[c.id])};}
const own=['owner'] as 'owner'[];
export function partnerRoutes(app:FastifyInstance){
  route(app,'PATCH','/api/v1/work/:t/partner-settings',{roles:own,schema:expected.extend({enabled:z.boolean()}).strict(),description:'Добровольное участие бизнеса в партнёрстве'},async({db,actor,p,b})=>{const t=await tenantById(db,p.t!);version(t,b.expectedVersion);await audit(db,t.id,actor.id,'campaign.settings',t.id,{enabled:b.enabled});return one(db,'UPDATE tenants SET partner_enabled=$2,version=version+1 WHERE id=$1 RETURNING *',[t.id,b.enabled]);});
  route(app,'GET','/api/v1/work/:t/campaigns',{roles:own,description:'Партнёрские кампании своей стороны'},async({db,p})=>{const all=await rows<Campaign&{source_name:string;target_name:string}>(db,'SELECT c.*,a.name source_name,b.name target_name FROM campaigns c JOIN tenants a ON a.id=c.source_tenant_id JOIN tenants b ON b.id=c.target_tenant_id WHERE source_tenant_id=$1 OR target_tenant_id=$1 ORDER BY c.created_at DESC',[p.t]);return list(await Promise.all(all.map(c=>campaignView(db,c))));});
  route(app,'POST','/api/v1/work/:t/campaigns',{roles:own,schema:campaignTerms.extend({sourceTenantId:id,targetTenantId:id}).strict(),description:'Создание черновика односторонней кампании'},async({db,actor,p,b})=>{
    if(b.sourceTenantId===b.targetTenantId||![b.sourceTenantId,b.targetTenantId].includes(p.t!))fail(422,'VALIDATION_ERROR','Вы должны быть одной из двух разных сторон');
    const tenants=await rows<Tenant>(db,"SELECT * FROM tenants WHERE id=ANY($1::uuid[]) AND status='published' AND partner_enabled",[[b.sourceTenantId,b.targetTenantId]]);if(tenants.length!==2)fail(409,'TENANT_UNAVAILABLE','Оба салона должны быть опубликованы и включить партнёрство');
    const c=(await one<Campaign>(db,'INSERT INTO campaigns(source_tenant_id,target_tenant_id) VALUES($1,$2) RETURNING *',[b.sourceTenantId,b.targetTenantId]))!;const terms=campaignTerms.parse(Object.fromEntries(Object.entries(b).filter(([k])=>!['sourceTenantId','targetTenantId'].includes(k))));await insertVersion(db,c,terms);await audit(db,p.t!,actor.id,'campaign.created',c.id);return campaignView(db,c);
  });
  route(app,'GET','/api/v1/work/:t/campaigns/:id',{roles:own,description:'Конкретные версии и согласования'},async({db,p})=>campaignView(db,await campaign(db,p.t!,p.id!)));
  route(app,'POST','/api/v1/work/:t/campaigns/:id/versions',{roles:own,schema:campaignTerms.extend({expectedVersion:z.number().int().positive()}).strict(),description:'Новая версия с сохранением действующих условий'},async({db,actor,p,b})=>{const c=await campaign(db,p.t!,p.id!);version(c,b.expectedVersion);if(c.status==='ended')fail(409,'INVALID_STATE_TRANSITION','Кампания завершена');if(c.pending_version_id)fail(409,'INVALID_STATE_TRANSITION','Сначала обработайте текущее предложение');if(await one(db,"SELECT 1 FROM campaign_versions WHERE campaign_id=$1 AND status='draft'",[c.id]))fail(409,'CONFLICT','Сначала согласуйте или удалите текущий черновик');const {expectedVersion,...terms}=b;await insertVersion(db,c,terms);await db.query('UPDATE campaigns SET version=version+1 WHERE id=$1',[c.id]);await audit(db,p.t!,actor.id,'campaign.version_created',c.id);return campaignView(db,await campaign(db,p.t!,p.id!));});
  route(app,'PATCH','/api/v1/work/:t/campaigns/:id/versions/:v',{roles:own,schema:campaignTerms.extend({expectedVersion:z.number().int().positive()}).strict(),description:'Редактирование только несогласованного черновика'},async({db,actor,p,b})=>{const c=await campaign(db,p.t!,p.id!);const v=required(await one<CampaignVersion>(db,'SELECT * FROM campaign_versions WHERE id=$1 AND campaign_id=$2',[p.v,c.id]));version(v,b.expectedVersion);if(v.status!=='draft'||c.status==='ended')fail(409,'INVALID_STATE_TRANSITION','Предложенная версия неизменяема');const {expectedVersion,...terms}=b;await validateTerms(db,c,terms);await audit(db,p.t!,actor.id,'campaign.version_updated',c.id);return one(db,'UPDATE campaign_versions SET source_service_ids=$2,target_service_ids=$3,discount_minor=$4,issue_from=$5,issue_until=$6,voucher_valid_days=$7,issue_limit=$8,terms_text=$9,terms_hash=$10,version=version+1 WHERE id=$1 RETURNING *',[v.id,b.sourceServiceIds,b.targetServiceIds,b.discountMinor,b.issueFrom,b.issueUntil,b.voucherValidDays,b.issueLimit,b.termsText,hash(canonical(terms))]);});
  route(app,'DELETE','/api/v1/work/:t/campaigns/:id/versions/:v',{roles:own,schema:expected,description:'Удаление несогласованного черновика'},async({db,actor,p,b})=>{const c=await campaign(db,p.t!,p.id!);const v=required(await one<CampaignVersion>(db,'SELECT * FROM campaign_versions WHERE id=$1 AND campaign_id=$2',[p.v,c.id]));version(v,b.expectedVersion);if(v.status!=='draft')fail(409,'INVALID_STATE_TRANSITION','Удалить можно только черновик');await db.query('DELETE FROM campaign_versions WHERE id=$1',[v.id]);await audit(db,p.t!,actor.id,'campaign.draft_deleted',c.id);return {ok:true};});
  for(const action of ['propose','accept','reject','withdraw']) route(app,'POST',`/api/v1/work/:t/campaigns/:id/versions/:v/${action}`,{roles:own,schema:expected.extend({termsHash:z.string().optional(),explicitConfirmation:z.boolean().optional(),reason:z.string().max(1000).optional()}).strict(),description:`Согласование версии: ${action}`},async({db,actor,p,b})=>{
    const c=await campaign(db,p.t!,p.id!);version(c,b.expectedVersion);const v=required(await one<CampaignVersion>(db,'SELECT * FROM campaign_versions WHERE id=$1 AND campaign_id=$2',[p.v,c.id]));if(c.status==='ended')fail(409,'INVALID_STATE_TRANSITION','Кампания завершена');
    if(action==='propose'||action==='accept') {
      const allowed=await rows(db,"SELECT id FROM tenants WHERE id=ANY($1::uuid[]) AND status='published' AND partner_enabled",[[c.source_tenant_id,c.target_tenant_id]]);if(allowed.length!==2)fail(409,'TENANT_UNAVAILABLE','Обе стороны должны включить партнёрство и опубликовать салон');
      await validateTerms(db,c,{sourceServiceIds:v.source_service_ids,targetServiceIds:v.target_service_ids,discountMinor:v.discount_minor,issueFrom:v.issue_from.toISOString(),issueUntil:v.issue_until.toISOString(),voucherValidDays:v.voucher_valid_days,issueLimit:v.issue_limit,termsText:v.terms_text});
    }
    if(action==='propose') {
      if(v.status!=='draft'||c.pending_version_id)fail(409,'INVALID_STATE_TRANSITION','Эта версия уже предложена или существует другое предложение');
      await db.query("UPDATE campaign_versions SET status='proposed',proposed_by_tenant_id=$2,version=version+1 WHERE id=$1",[v.id,p.t]);await db.query('INSERT INTO campaign_acceptances(version_id,tenant_id,user_id,terms_hash) VALUES($1,$2,$3,$4)',[v.id,p.t,actor.id,v.terms_hash]);await db.query("UPDATE campaigns SET pending_version_id=$2,status=CASE WHEN active_version_id IS NULL THEN 'proposed' ELSE status END,version=version+1 WHERE id=$1",[c.id,v.id]);
      const other=c.source_tenant_id===p.t?c.target_tenant_id:c.source_tenant_id;const owners=await rows<{user_id:string}>(db,"SELECT user_id FROM memberships WHERE tenant_id=$1 AND role='owner' AND status='active'",[other]);for(const o of owners)await notify(db,o.user_id,other,'campaign.proposed',c.id,'Партнёрская программа','Получены условия для согласования',{category:'work'});
    } else {
      if(v.status!=='proposed'||c.pending_version_id!==v.id)fail(409,'INVALID_STATE_TRANSITION','Версия не ожидает согласования');
      if(action==='withdraw'&&v.proposed_by_tenant_id!==p.t||action!=='withdraw'&&v.proposed_by_tenant_id===p.t)fail(403,'FORBIDDEN','Действие доступно другой стороне');
      if(action==='accept') {
        if(!b.explicitConfirmation||b.termsHash!==v.terms_hash)fail(409,'STALE_VERSION','Нужно подтвердить именно показанную версию условий');
        await db.query('INSERT INTO campaign_acceptances(version_id,tenant_id,user_id,terms_hash) VALUES($1,$2,$3,$4)',[v.id,p.t,actor.id,v.terms_hash]);
        if(c.active_version_id)await db.query("UPDATE campaign_versions SET status='ended',version=version+1 WHERE id=$1",[c.active_version_id]);
        await db.query("UPDATE campaign_versions SET status='active',version=version+1 WHERE id=$1",[v.id]);await db.query("UPDATE campaigns SET active_version_id=$2,pending_version_id=NULL,status='active',version=version+1 WHERE id=$1",[c.id,v.id]);
      } else {await db.query('UPDATE campaign_versions SET status=$2,version=version+1 WHERE id=$1',[v.id,action==='reject'?'rejected':'ended']);await db.query("UPDATE campaigns SET pending_version_id=NULL,status=CASE WHEN active_version_id IS NULL THEN 'rejected' ELSE status END,version=version+1 WHERE id=$1",[c.id]);}
    }
    await audit(db,p.t!,actor.id,`campaign.${action}`,c.id,{versionId:v.id,termsHash:v.terms_hash,reason:b.reason});return campaignView(db,await campaign(db,p.t!,p.id!));
  });
  for(const action of ['pause','resume','end'])route(app,'POST',`/api/v1/work/:t/campaigns/:id/${action}`,{roles:own,schema:command,description:`Управление выдачей: ${action}`},async({db,actor,p,b})=>{const c=await campaign(db,p.t!,p.id!);version(c,b.expectedVersion);if(c.status==='ended')fail(409,'INVALID_STATE_TRANSITION','Завершённую кампанию восстановить нельзя');if(action==='pause'){if(!b.reason)fail(422,'VALIDATION_ERROR','Укажите причину паузы');await db.query('INSERT INTO campaign_pauses(campaign_id,tenant_id,reason) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[c.id,p.t,b.reason]);}if(action==='resume')await db.query('DELETE FROM campaign_pauses WHERE campaign_id=$1 AND tenant_id=$2',[c.id,p.t]);if(action==='end'){await db.query("UPDATE campaigns SET status='ended',pending_version_id=NULL WHERE id=$1",[c.id]);await db.query("UPDATE campaign_versions SET status='ended',version=version+1 WHERE campaign_id=$1 AND status IN ('active','proposed','draft')",[c.id]);}await db.query('UPDATE campaigns SET version=version+1 WHERE id=$1',[c.id]);await audit(db,p.t!,actor.id,`campaign.${action}`,c.id,{reason:b.reason});return campaignView(db,await campaign(db,p.t!,p.id!));});
  route(app,'GET','/api/v1/work/:t/campaigns/:id/history',{roles:own,description:'История согласований обеих сторон без CRM'},async({db,p})=>{const c=await campaign(db,p.t!,p.id!);return {campaign:await campaignView(db,c),items:await rows(db,"SELECT action,details,created_at FROM audit_log WHERE object_id=$1 AND action LIKE 'campaign.%' ORDER BY created_at",[c.id])};});
  voucherRoutes(app);
}
function voucherRoutes(app:FastifyInstance){
  const projection='SELECT v.id,v.target_tenant_id,v.source_tenant_id,v.status,v.discount_minor,v.target_service_ids,v.terms_snapshot,v.issued_at,v.expires_at,v.reserved_booking_id,v.redeemed_booking_id,v.version,a.name source_name,b.name target_name,b.public_code target_code FROM vouchers v JOIN tenants a ON a.id=v.source_tenant_id JOIN tenants b ON b.id=v.target_tenant_id';
  route(app,'GET','/api/v1/me/vouchers',{description:'Личные купоны всех статусов'},async({db,actor,q})=>({items:await rows(db,`${projection} WHERE v.user_id=$1 AND ($2::text IS NULL OR v.status=$2) ORDER BY v.issued_at DESC LIMIT 100`,[actor.id,q.status||null]),revocationRequests:await rows(db,'SELECT r.id,r.reason,r.status,r.version,r.booking_version,r.booking_id,r.expires_at,b.price_minor_snapshot-b.discount_minor old_total_minor,b.price_minor_snapshot new_total_minor FROM revocation_requests r JOIN bookings b ON b.id=r.booking_id WHERE b.user_id=$1 AND r.status=\'pending\' ORDER BY r.created_at DESC',[actor.id]),nextCursor:null}));
  route(app,'GET','/api/v1/me/vouchers/:id',{description:'Собственный купон без внутренних данных другого салона'},async({db,actor,p})=>required(await one(db,`${projection} WHERE v.user_id=$1 AND v.id=$2`,[actor.id,p.id])));
  route(app,'GET','/api/v1/work/:t/vouchers',{roles:own,description:'Безопасная проекция купонов программы'},async({db,p})=>list(await rows(db,'SELECT id,campaign_id,status,discount_minor,issued_at,expires_at,version FROM vouchers WHERE source_tenant_id=$1 OR target_tenant_id=$1 ORDER BY issued_at DESC LIMIT 100',[p.t])));
  for(const reserved of [false,true])route(app,'POST',`/api/v1/work/:t/vouchers/:id/${reserved?'revocation-requests':'revoke'}`,{roles:own,schema:expected.extend({reason}).strict(),description:reserved?'Запрос клиенту на снятие зарезервированной скидки':'Отзыв свободного купона с причиной'},async({db,actor,p,b})=>{const v=required(await one<Voucher>(db,'SELECT * FROM vouchers WHERE id=$1 AND (source_tenant_id=$2 OR target_tenant_id=$2)',[p.id,p.t]));version(v,b.expectedVersion);if(v.status!==(reserved?'reserved':'issued'))fail(409,'INVALID_STATE_TRANSITION','Состояние купона не допускает это действие');
    if(reserved){const booking=required(await one<Booking>(db,'SELECT * FROM bookings WHERE id=$1',[v.reserved_booking_id]));const req=await one<{id:string}>(db,'INSERT INTO revocation_requests(voucher_id,booking_id,reason,booking_version) VALUES($1,$2,$3,$4) RETURNING *',[v.id,booking.id,b.reason,booking.version]);await notify(db,v.user_id,v.target_tenant_id,'voucher.revocation_request',req!.id,'Запрос изменения скидки','Цена изменится только после вашего подтверждения');await audit(db,p.t!,actor.id,'voucher.revocation_requested',v.id,{reason:b.reason});return req;}
    await db.query("UPDATE vouchers SET status='revoked',version=version+1 WHERE id=$1",[v.id]);await voucherRevision(db,v.id,'revoked',actor.id,b.reason);await notify(db,v.user_id,v.source_tenant_id,'voucher.revoked',v.id,'Купон отозван',b.reason);await audit(db,p.t!,actor.id,'voucher.revoked',v.id,{reason:b.reason});return {ok:true};
  });
  route(app,'POST','/api/v1/me/voucher-revocation-requests/:id/respond',{schema:expected.extend({accept:z.boolean(),expectedBookingVersion:z.number().int().positive()}).strict(),description:'Явное согласие или отказ клиента от изменения цены'},async({db,actor,p,b})=>{
    const req=required(await one<{id:string;voucher_id:string;booking_id:string;booking_version:number;version:number;status:string;expires_at:Date}>(db,'SELECT r.* FROM revocation_requests r JOIN bookings b ON b.id=r.booking_id WHERE r.id=$1 AND b.user_id=$2',[p.id,actor.id]));version(req,b.expectedVersion);if(req.status!=='pending'||req.expires_at<new Date())fail(409,'INVALID_STATE_TRANSITION','Запрос уже закрыт или истёк');
    const booking=required(await one<Booking>(db,'SELECT * FROM bookings WHERE id=$1',[req.booking_id]));version(booking,b.expectedBookingVersion);version(booking,req.booking_version);
    if(b.accept){const voucher=required(await one<Voucher>(db,'SELECT * FROM vouchers WHERE id=$1',[req.voucher_id]));if(voucher.status!=='reserved'||voucher.reserved_booking_id!==booking.id||booking.status!=='confirmed')fail(409,'INVALID_STATE_TRANSITION','Запись или резерв уже изменились');await db.query("UPDATE vouchers SET status='revoked',reserved_booking_id=NULL,version=version+1 WHERE id=$1",[voucher.id]);const updated=(await one<Booking>(db,'UPDATE bookings SET applied_voucher_id=NULL,discount_minor=0,version=version+1 WHERE id=$1 RETURNING *',[booking.id]))!;await voucherRevision(db,voucher.id,'revoked_with_consent',actor.id);await bookingRevision(db,updated,actor.id,'Клиент подтвердил снятие скидки');await bookingEvent(db,updated,'rescheduled');}
    await db.query('UPDATE revocation_requests SET status=$2,version=version+1 WHERE id=$1',[req.id,b.accept?'accepted':'declined']);await audit(db,booking.tenant_id,actor.id,'voucher.revocation_response',req.id,{accept:b.accept});return {ok:true};
  });
  route(app,'GET','/api/v1/work/:t/partner-exceptions',{roles:own,description:'Исключения своих партнёрских обязательств'},async({db,p})=>list(await rows(db,'SELECT e.id,e.voucher_id,e.reason,e.resolution,e.status,e.created_at FROM partner_exceptions e JOIN vouchers v ON v.id=e.voucher_id WHERE v.source_tenant_id=$1 OR v.target_tenant_id=$1 ORDER BY e.created_at DESC',[p.t])));
  route(app,'POST','/api/v1/work/:t/partner-exceptions/:id/resolve',{roles:own,schema:z.object({resolution:reason}).strict(),description:'Зафиксировать результат разбора без скрытого изменения денег'},async({db,actor,p,b})=>{required(await one(db,'SELECT e.id FROM partner_exceptions e JOIN vouchers v ON v.id=e.voucher_id WHERE e.id=$1 AND (v.source_tenant_id=$2 OR v.target_tenant_id=$2)',[p.id,p.t]));await audit(db,p.t!,actor.id,'campaign.exception_resolved',p.id!,{resolution:b.resolution});return one(db,"UPDATE partner_exceptions SET status='resolved',resolution=$2 WHERE id=$1 RETURNING *",[p.id,b.resolution]);});
}
