const phone=document.querySelector('#phone'),demo=document.querySelector('#demo');
const haircut={name:'Стрижка и укладка',duration:60,price:2400,masters:['Анна','Мария']},styling={name:'Укладка',duration:45,price:1600,masters:['Мария']};
let current='entry',trail=[],service={...haircut},master='Анна',time='12:00',result='success',reward=false,linked=false,activeBooking='1042',bookings={},prefs={},requestActive=false,channelPaused=false,windowStopped=false,visitEarly=false,candidate=null,catalog={...haircut},stopReason='Решение администратора';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const money=n=>n.toLocaleString('ru-RU')+' ₽';
const dateLabel=d=>{let [y,m,day]=d.split('-');return Number(day)+' '+({'09':'сентября','10':'октября'}[m]||m)};
const mins=s=>Number(s.split(':')[0])*60+Number(s.split(':')[1]);
const hh=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
function reset(){bookings={'1042':{id:'1042',date:'2026-10-02',time:'16:00',master:'Анна',...haircut}};service={...haircut};master='Анна';time='12:00';reward=false;linked=false;activeBooking='1042';requestActive=false;channelPaused=false;windowStopped=false;candidate=null;result='success';prefs={from:'2026-09-29',to:'2026-10-05',days:[1,2,3,4,5,6,7],start:'09:00',end:'18:00',masters:['Анна','Мария'],notice:'60'}}
function start(k){reset();trail=[];go(k,false)}
function go(k,push=true){if(k==='back'){go(trail.pop()||'entry',false);return}if(push&&current!==k)trail.push(current);if(k==='requestMove'){linked=true;const b=bookings[activeBooking];service={name:b.name,duration:b.duration,price:b.price,masters:b.masters};master=b.master;prefs={...prefs,to:b.date,masters:[b.master]}}if(k==='request'&&current==='empty'){linked=false;prefs.masters=[master]}if(k==='reward'){service={...haircut};master='Анна';reward=true}if(k==='store'){service={...haircut};reward=false}if(k==='closed'){requestActive=false;candidate=null}if(k==='paused'){channelPaused=true;candidate=null}if(k==='stopped'){windowStopped=true}current=k;render();if(k==='checking')setTimeout(finishAcceptance,850)}
function textReplace(a,b){phone.querySelectorAll('text').forEach(t=>{if(t.textContent===a)t.textContent=b})}
function region(y0,y1){[...phone.querySelector('svg').children].forEach(e=>{if(!['rect','text','a'].includes(e.tagName))return;let y=Number(e.getAttribute('y')??e.querySelector('rect')?.getAttribute('y')??-1);if(y>=y0&&y<=y1)e.remove()})}
function overlay(html,top=211){const d=document.createElement('div');d.className='summary';d.style.top=top+'px';d.innerHTML=html;phone.append(d);return d}
function controls(items){demo.innerHTML='<div class="tag">Пульт демонстрации · вне приложения</div>';items.forEach(([title,fn])=>{let b=document.createElement('button');b.textContent=title;b.onclick=fn;demo.append(b)})}
function createCandidate(){const b=linked?bookings[activeBooking]:null,now=new Date('2026-09-29T12:00:00+03:00').getTime();let list=prefs.masters.length?prefs.masters:service.masters;for(let day=new Date(prefs.from+'T00:00:00Z');day<=new Date(prefs.to+'T00:00:00Z');day.setUTCDate(day.getUTCDate()+1)){if(!prefs.days.includes(day.getUTCDay()||7))continue;let ds=day.toISOString().slice(0,10);for(let m=mins(prefs.start);m+service.duration<=mins(prefs.end);m+=15){let stamp=new Date(ds+'T'+hh(m)+':00+03:00').getTime();if(stamp<now+Number(prefs.notice)*60000)continue;if(b&&stamp>=new Date(b.date+'T'+b.time+':00+03:00').getTime())continue;candidate={date:ds,time:hh(m),master:list[0],...service};return true}}candidate=null;return false}
function simulateOffer(){if(!requestActive||channelPaused)return;if(!createCandidate()){document.querySelector('#status').textContent='В выбранном диапазоне пока нет подходящего окна.';return}go(linked?'offerMove':'offer')}
function finishAcceptance(){if(current!=='checking')return;if(result!=='success'){go(result);return}requestActive=false;const id=linked?activeBooking:String(Math.max(...Object.keys(bookings).map(Number))+1);bookings[id]={...candidate,id};activeBooking=id;go(linked?'moved':'bookings')}
function action(target,label){
 if(current==='store'&&target==='service'){service={...(label==='Укладка'?styling:haircut)};master=service.masters[0]}
 if(current==='slots'&&target==='slots'){master=label.includes('Мария')?'Мария':'Анна';render();return}
 if(current==='slots'&&target==='confirm'){time=label}
 if(['confirm','reward'].includes(current)&&target==='bookings'){const id=String(Math.max(...Object.keys(bookings).map(Number))+1);bookings[id]={...service,id,date:'2026-09-29',time,master,price:reward?0:service.price};activeBooking=id}
 if(current==='booking'&&target==='requestMove'){/* activeBooking retained */}
 if(current==='calendar'&&target==='visit'){visitEarly=label.startsWith('09:00')}
 if(current==='decline'&&target==='request'){candidate=null}
 if(current==='stopped'&&target==='calendar')windowStopped=true;
 if(current==='stop'&&target==='stopped'){stopReason=phone.querySelector('#reason').value.trim();if(!stopReason){phone.querySelector('#reason').reportValidity();return}}
 go(target)
}
function wire(){phone.querySelector('svg')?.setAttribute('role','group');phone.querySelectorAll('svg a').forEach(a=>{a.setAttribute('role','button');a.setAttribute('tabindex','0');const act=()=>action(a.getAttribute('href').slice(1),a.getAttribute('aria-label'));a.onclick=e=>{e.preventDefault();act()};a.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();act()}}})}
function render(){phone.innerHTML=FRAMES['A-'+current]||FRAMES['A-error'];demo.innerHTML='';document.querySelector('#status').textContent=FRAME_INDEX.find(f=>f.id==='A-'+current)?.title||'';
 if(['service','slots','empty','confirm','request','requestMove','offer','offerMove','requestSaved'].includes(current)){
 phone.querySelectorAll('text').forEach(t=>{t.textContent=t.textContent.replaceAll('Стрижка и укладка',service.name).replaceAll('2 400 ₽',money(service.price)).replaceAll('60 минут',service.duration+' минут').replaceAll('60 мин',service.duration+' мин')});}
 if(current==='service'){textReplace('Мастера услуги: Анна и Мария.','Мастера услуги: '+service.masters.join(', ')+'.');if(service.name==='Укладка')textReplace('Консультация, стрижка, укладка','Консультация и укладка волос')}
 if(current==='slots'){textReplace('Анна  ✓',master==='Анна'?'Анна  ✓':'Анна');textReplace('Мария',master==='Мария'?'Мария  ✓':'Мария');if(service.masters.length===1){const a=phone.querySelector('a[href="#slots"][aria-label="Анна  ✓"]');a?.remove();textReplace('Анна','Недоступна')}}
 if(['confirm','reward'].includes(current)){textReplace('29 сентября · 12:00–13:00',`29 сентября · ${time}–${hh(mins(time)+service.duration)}`);textReplace('Анна · Линия · Москва, UTC+3',master+' · Линия · Москва, UTC+3')}
 if(current==='bookings'){region(210,430);let list=Object.values(bookings).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const d=overlay('',215);d.style.background='transparent';d.style.padding='0';d.style.maxHeight='290px';d.style.overflowY='auto';list.forEach(b=>{let el=document.createElement('button');el.style='display:block;width:100%;text-align:left;background:white;border:0;border-radius:20px;padding:18px;margin-bottom:12px;color:#233f38;cursor:pointer;min-height:100px';el.innerHTML=`<strong>${dateLabel(b.date)} · ${b.time}</strong><br>${esc(b.name)} · ${esc(b.master)}<br>Подтверждена · № ${b.id} · ${money(b.price)}`;el.onclick=()=>{activeBooking=b.id;go('booking')};d.append(el)})}
 if(current==='booking'){const b=bookings[activeBooking];textReplace('ПОДТВЕРЖДЕНО · № 1042','ПОДТВЕРЖДЕНО · № '+b.id);textReplace('2 октября · 16:00',dateLabel(b.date)+' · '+b.time);textReplace('Стрижка и укладка · 60 минут',b.name+' · '+b.duration+' минут');textReplace('Линия · Анна · 2 400 ₽','Линия · '+b.master+' · '+money(b.price));}
 if(current==='decline'&&candidate)textReplace('Предложение на 29 сентября · 14:00','Предложение: '+dateLabel(candidate.date)+' · '+candidate.time);
 if(['request','requestMove'].includes(current)){if(linked){const b=bookings[activeBooking];textReplace(service.name+' · новая запись','Перенос № '+b.id+' · '+dateLabel(b.date)+', '+b.time);textReplace('Перенос записи № 1042 · 2 окт, 16:00',`Перенос № ${b.id} · ${dateLabel(b.date)}, ${b.time}`)}requestForm()}
 if(current==='requestSaved'){region(326,436);overlay(`<strong>${esc(service.name)}</strong><br>${prefs.from} — ${prefs.to}<br>${prefs.days.map(d=>['','Пн','Вт','Ср','Чт','Пт','Сб','Вс'][d]).join(' · ')} · ${prefs.start}–${prefs.end}<br>${esc(prefs.masters.join(', ')||'Любой мастер')} · за ${prefs.notice} мин<br>${linked?'Перенос № '+activeBooking+' · исходная запись сохранена':'Новая запись только после принятия'}`,326);if(channelPaused){textReplace('Запрос создан','Запрос на паузе');textReplace('Ждём подходящее время','Бот MAX недоступен');controls([['Симуляция: бот снова запущен',()=>{channelPaused=false;render()}]])}else controls([['Симуляция: пришло предложение',simulateOffer],['Симуляция: бот недоступен',()=>go('paused')]])}
 if(['offer','offerMove'].includes(current)&&candidate){textReplace('Сегодня · 14:00–15:00',`${dateLabel(candidate.date)} · ${candidate.time}`);textReplace(service.name+' · Анна',service.name+' · '+candidate.master);textReplace('Линия · Москва, UTC+3',candidate.duration+' мин · до '+hh(mins(candidate.time)+candidate.duration)+' · Москва');textReplace('ПРЕДЛОЖЕНИЕ · 29 СЕНТЯБРЯ','ПРЕДЛОЖЕНИЕ · МОСКВА, UTC+3');if(linked){const b=bookings[activeBooking];textReplace('Перенос с 2 октября, 16:00.',`Перенос с ${dateLabel(b.date)}, ${b.time}.`);textReplace('Изменим запись № 1042, второй не будет.',`Изменим запись № ${b.id}, второй не будет.`)}controls([['Результат: время доступно',()=>result='success'],['Результат: время занято',()=>result='lost'],['Результат: срок истёк',()=>result='expired']])}
 if(current==='moved'){const b=bookings[activeBooking];textReplace('ГОТОВО · № 1042','ГОТОВО · № '+b.id);textReplace('29 сентября · 14:00',dateLabel(b.date)+' · '+b.time);textReplace('Линия · Анна · 60 минут',`Линия · ${b.master} · ${b.duration} минут`);textReplace('2 400 ₽ · оплата в салоне',money(b.price)+' · оплата в салоне');textReplace('Время 2 октября, 16:00 освобождено.','Предыдущее время освобождено.');textReplace('У вас одна запись № 1042.','У вас одна запись № '+b.id+'.')}
 if(['lost','expired'].includes(current)){if(linked){const b=bookings[activeBooking];textReplace('запись на 2 октября, 16:00 сохранена.',`запись № ${b.id} сохранена.`)}else{textReplace('Если вы переносили запись, исходная','Новая запись не создана.');textReplace('запись на 2 октября, 16:00 сохранена.','Можно дождаться другого предложения.')}}
 if(current==='calendar'&&windowStopped)textReplace('Ждём ответ →','Остановлено · время свободно →');
 if(current==='window'&&windowStopped){textReplace('Ждём ответ до 12:10','Остановлено администратором');textReplace('02   Предложение отправлено · ждём','02   Предложение отозвано');textReplace('03   Следующий · ещё не отправлено','03   Не отправлено · окно закрыто');region(674,722);overlay('Окно остановлено. Время доступно<br>для обычной записи.',674)}
 if(current==='visit'&&visitEarly){textReplace('Запись № 1041','Запись № 1040');textReplace('29 сентября · 12:00','29 сентября · 09:00');textReplace('Анна Смирнова · стрижка и укладка','Ирина Волкова · стрижка и укладка')}
 if(current==='crm'&&visitEarly){textReplace('Анна Смирнова','Ирина Волкова');textReplace('8 визитов · постоянный','1 визит · новый клиент');textReplace('Последний: 12 сентября','Первый визит: 29 сентября');textReplace('Ближайший: 29 сентября, 12:00','Ближайший: 29 сентября, 09:00');textReplace('Предпочитает утреннее время.','Заметок пока нет.');textReplace('4 / 5 в новом цикле','0 / 5 в текущем цикле');textReplace('Доступна 1 награда прошлого цикла','Доступных наград нет');region(551,645)}
 if(current==='catalog')catalogForm();if(current==='stop')stopForm();
 if(current==='store')controls([['Показать ошибку сети',()=>go('error')],['Пустой список записей',()=>go('noBookings')]]);
 if(current==='crm')controls([['Пустая CRM',()=>go('noCRM')]]);wire();
}
function requestForm(){region(193,737);const b=linked?bookings[activeBooking]:null;const f=document.createElement('form');f.id='form';f.innerHTML=`<div class="row"><div class="field"><label for="from">С даты</label><input id="from" type="date" value="${prefs.from}" min="2026-09-29" max="2026-10-28" required></div><div class="field"><label for="to">По дату</label><input id="to" type="date" value="${prefs.to}" min="2026-09-29" max="${b?b.date:'2026-10-28'}" required></div></div><fieldset><legend>Дни недели</legend><div class="days">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((v,i)=>`<label><input name="day" value="${i+1}" type="checkbox" ${prefs.days.includes(i+1)?'checked':''}><span>${v}</span></label>`).join('')}</div></fieldset><div class="row"><div class="field"><label for="start">Визит не раньше</label><input id="start" type="time" value="${prefs.start}" required></div><div class="field"><label for="end">Закончить до · Москва</label><input id="end" type="time" value="${prefs.end}" required></div></div><fieldset><legend>Мастера · никто не выбран = любой</legend><div class="row">${service.masters.map(v=>`<label class="check"><input name="master" value="${v}" type="checkbox" ${prefs.masters.includes(v)?'checked':''}>${v}</label>`).join('')}</div></fieldset><div class="field"><label for="notice">Минимум до визита · по умолчанию 1 час</label><select id="notice">${[['60','1 час'],['120','2 часа'],['360','6 часов'],['1440','1 день']].map(([v,t])=>`<option value="${v}" ${prefs.notice===v?'selected':''}>${t}</option>`).join('')}</select></div><p class="hint">Это не запись. Время не удерживается.${b?' Перенос строго раньше '+dateLabel(b.date)+', '+b.time+'.':''}</p><label class="check"><input id="consent" type="checkbox" required>Согласен на предложения этого запроса</label><p id="validation" role="alert"></p><button class="primary">Создать запрос</button>`;phone.append(f);f.onsubmit=e=>{e.preventDefault();const v=id=>f.querySelector('#'+id).value;let days=[...f.querySelectorAll('[name=day]:checked')].map(i=>Number(i.value));let error=!days.length?'Выберите хотя бы один день недели.':v('to')<v('from')?'Конечная дата должна быть не раньше начальной.':mins(v('end'))-mins(v('start'))<service.duration?`Для услуги нужен диапазон от ${service.duration} минут.`:'';if(error){f.querySelector('#validation').textContent=error;return}prefs={from:v('from'),to:v('to'),days,start:v('start'),end:v('end'),masters:[...f.querySelectorAll('[name=master]:checked')].map(i=>i.value),notice:v('notice')};requestActive=true;go('requestSaved')};}
function catalogForm(){textReplace('Стрижка и укладка',catalog.name);textReplace('60 минут · Анна, Мария',catalog.duration+' минут · Анна, Мария');textReplace('2 400 ₽ · активна',money(catalog.price)+' · активна');region(351,720);let f=document.createElement('form');f.id='form';f.className='compact';f.innerHTML=`<label for="service">Название</label><input id="service" value="${esc(catalog.name)}" maxlength="28" required><div class="row" style="margin-top:22px"><div><label for="duration">Минуты</label><input id="duration" type="number" min="5" max="480" value="${catalog.duration}" required></div><div><label for="price">Цена, ₽</label><input id="price" type="number" min="0" max="99999" value="${catalog.price}" required></div></div><p class="hint" style="margin:35px 0">Новая цена — для новых записей. Подтверждённые сохраняют свою цену.</p><button class="primary">Сохранить изменения</button>`;phone.append(f);f.onsubmit=e=>{e.preventDefault();catalog={...catalog,name:f.querySelector('#service').value,duration:Number(f.querySelector('#duration').value),price:Number(f.querySelector('#price').value)};go('saved')}}
function stopForm(){let f=document.createElement('div');f.style='position:absolute;top:380px;left:24px;width:342px';f.innerHTML='<label for="reason" style="position:absolute;left:-10000px">Причина остановки</label><input id="reason" value="Решение администратора" required>';phone.append(f)}
reset();go('entry',false);
